/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CatalogView: typeof import('./src/components/CatalogView.vue')['default']
    CompareTable: typeof import('./src/components/CompareTable.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    HelpTip: typeof import('./src/components/HelpTip.vue')['default']
    PriceCurve: typeof import('./src/components/PriceCurve.vue')['default']
    ReportView: typeof import('./src/components/ReportView.vue')['default']
    ReviewView: typeof import('./src/components/ReviewView.vue')['default']
    RuleEditor: typeof import('./src/components/RuleEditor.vue')['default']
    ScoreRadar: typeof import('./src/components/ScoreRadar.vue')['default']
    SettingsView: typeof import('./src/components/SettingsView.vue')['default']
    SnapshotPanel: typeof import('./src/components/SnapshotPanel.vue')['default']
    TracePanel: typeof import('./src/components/TracePanel.vue')['default']
    WorkbenchView: typeof import('./src/components/WorkbenchView.vue')['default']
  }
}
